apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-teste-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-no-delete
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: teste-pod
spec:
  securityContext:
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
  containers:
    - name: my-container
      image: nginx:latest  # Replace with your desired container imag
      volumeMounts:
        - name: my-pvc-volume
          mountPath: /arquivos  # The path inside the container where the PVC will be mounted
  volumes:
    - name: my-pvc-volume
      persistentVolumeClaim:
        claimName: pvc-teste-2