apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-teste-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-no-delete
  resources:
    requests:
      storage: 10Gi
